version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository
      - codecov/upload
      - run: mkdir -p ./badges
      - run: cp target/site/badges/*.svg ./badges/
      - store_artifacts:
          path: ./badges
      - run:
          name: Generate Javadoc
          command: mvn javadoc:jar
      - run:
          name: Publish Javadoc to GitHub Pages
          command: |
            mkdir -p docs/javadoc
            mv target/site/apidocs/* docs/javadoc
            echo 'www.example.com' > CNAME
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
            git init
            git add -A
            git commit -m "Publish Javadoc to GitHub Pages"
            git push --force --quiet "https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git" master:gh-pages
    deploy:
      production:
        branch: master
        commands:
          - ./deploy.sh
workflows:
  build-and-test:
    jobs:
      - test-java
